# Generated by Django 4.2.6 on 2023-10-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='name',
        ),
    ]
