# Generated by Django 4.2.3 on 2023-11-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo_project.registration'),
        ),
    ]
